# Generated by Django 4.2.4 on 2023-09-02 11:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_name",
                    models.CharField(max_length=128, verbose_name="device name"),
                ),
                (
                    "serial_no",
                    models.CharField(
                        max_length=16,
                        unique=True,
                        validators=[django.core.validators.MinLengthValidator(16)],
                        verbose_name="serial no.",
                    ),
                ),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("MOB", "Samartphone"),
                            ("LAP", "Laptop"),
                            ("TAB", "Tablet"),
                        ],
                        max_length=128,
                        verbose_name="device type",
                    ),
                ),
                (
                    "availability",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Avaialble"),
                            ("IN_USE", "Occupied"),
                            ("MAINTENANCE", "Under maintenance or being repaired"),
                            ("LOST", "Lost, stolen or permamnently damaged"),
                        ],
                        max_length=128,
                        verbose_name="device availability",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee_name",
                    models.CharField(max_length=128, verbose_name="employee name"),
                ),
                (
                    "employee_id",
                    models.CharField(
                        max_length=128,
                        unique=True,
                        validators=[django.core.validators.MinLengthValidator(8)],
                        verbose_name="employee id",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("ITC", "Information Technology"),
                            ("HRC", "Human Resource"),
                            ("DEV", "Software Development"),
                            ("SQA", "Software Quality Assurance"),
                            ("MKT", "Sales and Marketing"),
                            ("FIN", "Finance"),
                        ],
                        max_length=128,
                        verbose_name="department",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeviceLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "log_type",
                    models.CharField(
                        choices=[
                            ("ASSIGNED", "Assigned to an employee"),
                            ("RETURNED", "Returned by the assigned employee"),
                            ("SENT_FOR_MAINTENANCE", "Sent for maintenance"),
                            ("RETURNED_FROM_MAINTENANCE", "Returned from maintenance"),
                            ("LOST", "Went missing"),
                            ("FOUND", "Found"),
                        ],
                        max_length=128,
                        verbose_name="log type",
                    ),
                ),
                ("details", models.TextField(blank=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.device"
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.employee",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="device",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="core.employee"
            ),
        ),
    ]
